fix(color-edit): fix of displaying opacity count below 58%
Tinkoff/taiga-ui pull request #1282
Opened 2022-01-30 14:53 UTC by alexishere24

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Opacity count input doesnt work correctly with  opacity below 58%

Closes # 

## What is the new behavior?

Opacity count input work correctly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-01-30 15:31 UTC, splincode commented
why `package-lock.json` was update?

2022-01-31 13:12 UTC, waterplea requested changes
Small comment and also please rollback the `package-lock` change. Use `npm ci` in future so it does not change the lock file.

2022-01-31 13:12 UTC, waterplea commented on projects/addon-editor/components/color-selector/color-edit/color-edit.component.ts
> +        return round(this.color[3] * 100);
Let's just use `Math.round`

2022-02-02 14:14 UTC, vladimirpotekhin commented
https://github.com/Tinkoff/taiga-ui/pull/1312

2022-02-02 14:14 UTC, closed without merging