feat(addon-table): `TableSort` add new pipe to externalize row iteration
Tinkoff/taiga-ui pull request #1483
Opened 2022-03-03 15:32 UTC by waterplea

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #892

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

2022-03-03 15:39 UTC, splincode approved these changes

2022-03-04 07:14 UTC, nsbarsukov requested changes

2022-03-04 07:14 UTC, nsbarsukov commented on projects/demo/src/modules/tables/table/examples/5/index.ts
> +        FIRST[Math.floor(Math.random() * 10)]
please add this example to cypress exclusions

https://github.com/Tinkoff/taiga-ui/blob/d1b22cccdf65b3644be670208719834b0fe53e2d/projects/demo-integrations/cypress/support/exclusions.ts#L5

2022-03-04 07:18 UTC, nsbarsukov commented on projects/addon-table/components/table/tbody/tbody.component.ts
> +import {TuiTableSortPipe} from '@taiga-ui/addon-table/components';
probably, this line breaks build

2022-03-04 08:36 UTC, nsbarsukov approved these changes

2022-03-04 10:08 UTC, vladimirpotekhin approved these changes

2022-03-04 10:17 UTC, merged