feat(kit): `TUI_AVATAR_OPTIONS` default options configuration for `Avatar`
Tinkoff/taiga-ui pull request #1600
Opened 2022-04-06 19:42 UTC by zarghamkhandev

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Partially implements https://github.com/Tinkoff/taiga-ui/issues/133

## What is the new behavior?

Default avatar options can be set via a provider. This is a partial implementation of https://github.com/Tinkoff/taiga-ui/issues/133

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-04-07 06:30 UTC, nsbarsukov requested changes
Thanks for PR!

2022-04-07 06:30 UTC, nsbarsukov commented on projects/kit/components/avatar/avatar-options.ts
> +import {TuiSizeXS, TuiSizeXXL} from '@taiga-ui/core/types';
```suggestion
import {TuiSizeXS, TuiSizeXXL} from '@taiga-ui/core';
```

2022-04-07 06:30 UTC, nsbarsukov commented on projects/kit/components/avatar/tests/avatar-options.spec.ts
> +} from '@taiga-ui/kit';
Declare them as relative imports

2022-04-07 08:37 UTC, splincode commented
Hello, please, rebase with main branch before

2022-04-07 21:15 UTC, zarghamkhandev commented on projects/kit/components/avatar/tests/avatar-options.spec.ts
> +} from '@taiga-ui/kit';
done ✅

2022-04-08 07:22 UTC, nsbarsukov approved these changes

2022-04-08 07:24 UTC, splincode approved these changes

2022-04-08 09:10 UTC, waterplea approved these changes
Thank you for this PR!

2022-04-08 09:10 UTC, merged