fix(kit): use passive event listener for prevent scroll-blocking
Tinkoff/taiga-ui pull request #1821
Opened 2022-05-26 19:11 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1808

## What is the new behavior?

No warnings

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-05-26 19:11 UTC, splincode commented on projects/kit/abstract/slider/slider.ts
> +    onTouchStart(event: Event): void {
https://github.com/Tinkoff/ng-event-plugins/issues/42

2022-05-27 07:37 UTC, nsbarsukov approved these changes

2022-05-27 07:44 UTC, nsbarsukov requested changes

2022-05-27 07:44 UTC, nsbarsukov commented on projects/kit/abstract/slider/slider.ts
> +    onTouchStart(event: Event): void {
this function contains
```
event.preventDefault();
```

it cannot be passive

2022-05-27 07:45 UTC, nsbarsukov commented on projects/kit/abstract/slider/slider.ts
> +    onTouchStart(event: Event): void {
this file is legacy file anyway (it will be deleted in v3.0).

2022-05-27 08:06 UTC, closed without merging