ci: support `prefer-optional-chain`
Tinkoff/taiga-ui pull request #1848
Opened 2022-06-01 07:58 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [x] Build or CI related changes
- [ ] Documentation content changes

2022-06-02 11:35 UTC, nsbarsukov approved these changes

2022-06-03 07:28 UTC, waterplea requested changes
A few small comments

2022-06-03 07:28 UTC, waterplea commented on projects/addon-editor/components/toolbar/toolbar.component.ts
> +        return first?.nativeFocusableElement ? first.nativeFocusableElement : null;
first?.nativeFocusableElement || null

2022-06-03 07:28 UTC, waterplea commented on projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
> +        return this.context.data?.min ? this.context.data.min : TUI_FIRST_DAY;
this.context.data?.min || TUI_FIRST_DAY

2022-06-03 07:28 UTC, waterplea commented on projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
> +        return this.context.data?.max ? this.context.data.max : TUI_LAST_DAY;
Same

2022-06-03 07:28 UTC, waterplea commented on projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
> +        return this.context.data?.disabledItemHandler
Same

2022-06-03 07:28 UTC, waterplea commented on projects/demo/src/modules/components/hosted-dropdown/examples/1/index.ts
Unnecessary empty line now

2022-06-03 07:28 UTC, waterplea commented on projects/demo/src/modules/components/hosted-dropdown/examples/2/index.ts
Here as well

2022-06-03 07:28 UTC, waterplea commented on projects/testing/utils/active-element.ts
> +    return document.activeElement?.textContent
document.activeElement?.textContent?.trim() || ''

2022-06-03 09:30 UTC, splincode commented on projects/addon-editor/components/toolbar/toolbar.component.ts
> +        return first?.nativeFocusableElement ? first.nativeFocusableElement : null;
fixed

2022-06-03 09:30 UTC, splincode commented on projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
> +        return this.context.data?.min ? this.context.data.min : TUI_FIRST_DAY;
fixed

2022-06-03 09:30 UTC, splincode commented on projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
> +        return this.context.data?.max ? this.context.data.max : TUI_LAST_DAY;
fixed

2022-06-03 09:30 UTC, splincode commented on projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
> +        return this.context.data?.disabledItemHandler
fixed

2022-06-03 09:31 UTC, splincode commented on projects/demo/src/modules/components/hosted-dropdown/examples/1/index.ts
fixed

2022-06-03 09:31 UTC, splincode commented on projects/demo/src/modules/components/hosted-dropdown/examples/2/index.ts
fixed

2022-06-03 09:31 UTC, splincode commented on projects/testing/utils/active-element.ts
> +    return document.activeElement?.textContent
fixed

2022-06-03 12:03 UTC, waterplea approved these changes

2022-06-03 12:04 UTC, merged