refactor: remove FrontEndExample
Tinkoff/taiga-ui pull request #1872
Opened 2022-06-07 07:19 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

2022-06-07 07:46 UTC, nsbarsukov commented on projects/demo/src/modules/charts/line-days-chart/line-days-chart.component.ts
> +        Pipe: import('!!raw-loader!./examples/2/pipe.ts'),
```suggestion
       'pipe.ts': import('!!raw-loader!./examples/2/pipe.ts'),
```
(stackblitz)

2022-06-07 07:46 UTC, nsbarsukov commented on projects/demo/src/modules/charts/pie-chart/pie-chart.component.ts
> +    readonly exampleHtml = import('!!raw-loader!./examples/import/insert-template.txt');
`*.md` ?

2022-06-07 07:46 UTC, nsbarsukov commented on projects/demo/src/modules/components/svg/svg.component.ts
> +    readonly exampleHtml = import('!!raw-loader!./examples/import/insert-template.txt');
md ?

2022-06-07 07:46 UTC, nsbarsukov commented on projects/demo/src/modules/tables/reorder/examples/import/import-module.md
> +import {TuiReorderModule} from '@taiga-ui/addon-table/components/reorder';
```suggestion
import {TuiReorderModule} from '@taiga-ui/addon-table';
```

2022-06-07 07:46 UTC, nsbarsukov commented on projects/demo/src/modules/tables/reorder/reorder.component.ts
> +    readonly exampleHtml = import('!!raw-loader!./examples/import/insert-template.txt');
md ?

2022-06-07 07:46 UTC, nsbarsukov commented on projects/demo/src/modules/tables/resizable-column/examples/import/import-module.md
> +import {TuiResizableColumnModule} from '@taiga-ui/addon-table/components/resizableColumn';
```suggestion
import {TuiResizableColumnModule} from '@taiga-ui/addon-table';
```

2022-06-07 11:22 UTC, splincode commented on projects/demo/src/modules/charts/line-days-chart/line-days-chart.component.ts
> +        Pipe: import('!!raw-loader!./examples/2/pipe.ts'),
fixed

2022-06-07 11:22 UTC, splincode commented on projects/demo/src/modules/charts/pie-chart/pie-chart.component.ts
> +    readonly exampleHtml = import('!!raw-loader!./examples/import/insert-template.txt');
fixed

2022-06-07 11:22 UTC, splincode commented on projects/demo/src/modules/components/svg/svg.component.ts
> +    readonly exampleHtml = import('!!raw-loader!./examples/import/insert-template.txt');
fixed

2022-06-07 11:22 UTC, splincode commented on projects/demo/src/modules/tables/reorder/examples/import/import-module.md
> +import {TuiReorderModule} from '@taiga-ui/addon-table/components/reorder';
fixed

2022-06-07 11:23 UTC, splincode commented on projects/demo/src/modules/tables/reorder/reorder.component.ts
> +    readonly exampleHtml = import('!!raw-loader!./examples/import/insert-template.txt');
fixed

2022-06-07 11:23 UTC, splincode commented on projects/demo/src/modules/tables/resizable-column/examples/import/import-module.md
> +import {TuiResizableColumnModule} from '@taiga-ui/addon-table/components/resizableColumn';
fixed

2022-06-08 04:52 UTC, nsbarsukov reviewed
File

https://github.com/Tinkoff/taiga-ui/blob/splincode/chore/demo/frontend-example/projects/demo/src/modules/charts/bar-chart/examples/import/insert-template.md

does not have code block

2022-06-08 05:03 UTC, nsbarsukov approved these changes
🔥

2022-06-08 05:03 UTC, nsbarsukov commented on projects/demo/src/modules/services/table-bar/examples/import/service-usage-html.md
> +<ng-template #tableBarTemplate> <p>Template</p> </ng-template>
add code block

2022-06-08 06:05 UTC, nsbarsukov requested changes
Cypress tests logs:
```
1) Demo
        components/accordion:
      AssertionError: Timed out retrying after 10000ms:
      Expected to find element: `.t-example`, but never found it.
      Queried from element: <tui-doc-example#single.ng-star-inserted>
```

2022-06-08 07:54 UTC, splincode commented on projects/demo/src/modules/services/table-bar/examples/import/service-usage-html.md
> +<ng-template #tableBarTemplate> <p>Template</p> </ng-template>
fixed

2022-06-08 07:54 UTC, splincode commented
@nsbarsukov fixed

2022-06-09 06:58 UTC, vladimirpotekhin approved these changes

2022-06-09 07:52 UTC, merged

2022-06-09 07:52 UTC, nsbarsukov requested changes
+ `projects/demo/src/modules/charts/bar-chart/examples/import/insert-template.md`

2022-06-09 07:52 UTC, nsbarsukov commented on projects/demo/src/modules/components/checkbox-block/examples/import/insert-template.md
> +<div [formGroup]="testForm">
nit:
```suggestion
<form [formGroup]="testForm">
```

2022-06-09 07:52 UTC, nsbarsukov commented on projects/demo/src/modules/components/checkbox-labeled/examples/import/insert-template.md
> +<div [formGroup]="testForm">
nit:
```suggestion
<form [formGroup]="testForm">
```

2022-06-09 07:52 UTC, nsbarsukov commented on projects/demo/src/modules/components/input-phone-international/examples/import/import-module.md
> +@NgModule({ imports: [ ... FormsModule, ReactiveFormsModule, TuiInputPhoneInternationalModule ], ...
add code block

2022-06-09 07:52 UTC, nsbarsukov commented on projects/demo/src/modules/components/marker-icon/examples/import/import-module.md
> +@NgModule({ imports: [ ... TuiMarkerIconModule ], ...
add code block

2022-06-09 07:52 UTC, nsbarsukov commented on projects/demo/src/modules/components/radio-block/examples/import/insert-template.md
> +<div [formGroup]="testForm">
nit:
```suggestion
<form [formGroup]="testForm">
```

and closing tag too

2022-06-09 07:52 UTC, nsbarsukov commented on projects/demo/src/modules/components/radio-labeled/examples/import/insert-template.md
> +<div [formGroup]="testForm">
nit:
```suggestion
<form [formGroup]="testForm">
```

2022-06-09 07:52 UTC, nsbarsukov commented on projects/demo/src/modules/components/toggle/examples/import/insert-template.md
> +<div [formGroup]="testForm">
nit:
```suggestion
<form [formGroup]="testForm">
```