feat(kit): detect pdf is not visible in browser
Tinkoff/taiga-ui pull request #1889
Opened 2022-06-09 17:02 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1866

## What is the new behavior?

https://user-images.githubusercontent.com/12021443/172903333-3dc1ea34-f114-47cd-829d-06a227e70970.mov

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-06-10 04:34 UTC, nsbarsukov requested changes
Your PR name: `feat(kit): detect pdf is not visible in browser`

Should we rename it to `fix(kit): ...` ?

2022-06-10 04:34 UTC, nsbarsukov commented on projects/kit/components/pdf-viewer/pdf-viewer.template.html
> +        The PDF could not be loaded, there may be a network problem, or your
Let's put it inside `@taiga-ui/i18n`:
https://github.com/Tinkoff/taiga-ui/blob/7b303d12621a7270e6a2b9d00651b76739486274/projects/i18n/interfaces/language.ts#L23

For example, property `unavailablePdfError` (or something shorter)

2022-06-10 04:34 UTC, nsbarsukov commented on projects/kit/components/pdf-viewer/pdf-viewer.component.ts
> +                    this.cd.detectChanges();
We can deal with it without extra explicit subscription and extra selector.
Use `*tuiLet` inside template to subscribe to this observable.
Then in template:
```html
<header class="t-header" *tuiLet="iframe$ | async as iframeAvailable">
    ...
    <section
        polymorpheus-outlet
        class="t-content"
        [content]="iframeAvailable ? context.content : errorMessageRef"
        <iframe
            class="t-iframe"
            [class.t-iframe_hidden]="!iframeAvailable"
        ></iframe>
    </section>
    
    <ng-template #errorMessageRef>...</ng-template>
</header>

```

2022-06-10 04:34 UTC, nsbarsukov commented on projects/kit/components/pdf-viewer/pdf-viewer.component.ts
> +        } else if (isFirefox(this.windowRef.navigator.userAgent)) {
use 
```ts
import {USER_AGENT} from '@ng-web-apis/common';
// ...
@Inject(USER_AGENT) private readonly userAgent: string,
```

2022-06-10 04:34 UTC, nsbarsukov commented on projects/kit/components/pdf-viewer/pdf-viewer.component.ts
> +            return contentWindow.document.body.innerHTML.includes('embed');
Could you please add some code-comments here ?

Honestly, i dont understand what happens here :(

2022-06-10 04:40 UTC, nsbarsukov commented on projects/kit/components/pdf-viewer/pdf-viewer-options.ts
> +    readonly errorMessage?: string;
Let's make it as just `error` (with type `PolymorpheusContent`).

Our users can decide to put some custom content.
For example, error-page component.

2022-06-10 09:02 UTC, vladimirpotekhin commented
If user's browser setting "download pdf", he could download it and read before. Now he can't do it? (3th example)

2022-06-14 16:12 UTC, splincode commented
https://github.com/Tinkoff/taiga-ui/pull/1920

2022-06-14 16:12 UTC, closed without merging