fix(addon-editor): dropdown shouldn't visible outside of editor area
Tinkoff/taiga-ui pull request #1934
Opened 2022-06-16 16:19 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1302

https://user-images.githubusercontent.com/12021443/174117814-3695e928-45d9-4427-9e1f-795861762fda.mov

## What is the new behavior?

https://user-images.githubusercontent.com/12021443/174117929-076bb5f4-fa07-465f-92c9-f211046a3c8c.mov

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-06-17 09:31 UTC, waterplea requested changes
I don't like that we add an input for host. Directive works through service, we can just override this service in DI for Editor and thus making dropdown show in a different host.

2022-06-17 13:57 UTC, splincode commented
@waterplea I tried to do it through the service, but I it doesn't work

2022-06-21 07:00 UTC, nsbarsukov approved these changes

2022-06-23 07:24 UTC, waterplea approved these changes

2022-06-23 07:25 UTC, merged