[WIP] ci: use `tui` prefix for exported functions
Tinkoff/taiga-ui pull request #2014
Opened 2022-06-28 16:53 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [x] Build or CI related changes
- [ ] Documentation content changes

2022-07-04 08:56 UTC, waterplea reviewed
Can we check if all these input assertions can now just be inline arrow functions? It is exported just so AOT compilation work, but maybe it's not necessary anymore. Or maybe it won't be once we publish in Ivy 🤔 In this case we can skip them until 3.0, they are internal functions exported just so compiler works, nobody uses them externally.

2022-07-04 15:32 UTC, splincode commented on projects/addon-charts/components/bar-chart/bar-chart.component.ts
> +    return value.every(array => array.length === value[0].length);
Do you mean, we can delete `@tuiDefaultProp(valueAssertion, VALUE_ERROR)` line?

2022-07-05 10:30 UTC, waterplea approved these changes

2022-07-05 12:45 UTC, splincode commented on projects/addon-charts/utils/control-point.ts
> +export const tuiControlPoint = controlPoint;
in the next PR

2022-07-05 13:04 UTC, nsbarsukov requested changes

2022-07-05 13:11 UTC, splincode commented on projects/kit/components/input-phone-international/const/countries.ts
> +export const tuiCountriesMasksReducer = countriesMasksReducer;
fixed

2022-07-05 13:11 UTC, splincode commented on projects/core/utils/format/pluralize.ts
> +export const tuiPluralize = pluralize;
fixed

2022-07-05 13:12 UTC, splincode commented on projects/addon-charts/utils/draw-line.ts
> + * @deprecated: use {@link tuiControlPoint} instead
fixed

2022-07-05 13:20 UTC, nsbarsukov approved these changes

2022-07-05 14:16 UTC, merged