fix(core): align to baseline value decoration postfix
Tinkoff/taiga-ui pull request #2070
Opened 2022-07-07 10:22 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2065 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/12021443/177751890-5f4ae20e-28fa-4c01-97ce-4ded99f9349d.png">

## What is the new behavior?

<img width="425" alt="image" src="https://user-images.githubusercontent.com/12021443/177751799-7ef9c367-4857-49b3-aae4-365c5c234a89.png">

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-07-07 10:44 UTC, waterplea approved these changes

2022-07-07 10:46 UTC, vladimirpotekhin approved these changes

2022-07-07 16:16 UTC, waterplea requested changes
Need to fix right alignment.

2022-07-07 16:23 UTC, splincode commented
@waterplea updated

2022-07-08 11:57 UTC, waterplea approved these changes

2022-07-08 12:14 UTC, merged