refactor!: remove deprecated core-enums, TuiColor, colorFallback, DEFAULT_COLORS, TuiColorHandler
Tinkoff/taiga-ui pull request #2158
Opened 2022-07-20 07:06 UTC by vladimirpotekhin

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes # 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

2022-07-20 07:24 UTC, splincode approved these changes

2022-07-21 06:32 UTC, nsbarsukov approved these changes

2022-07-25 18:01 UTC, waterplea requested changes

2022-07-25 18:01 UTC, waterplea commented on projects/demo/src/modules/themes/bootstrap/bootstrap.style.less
> +        &:hover:not(._no-hover),
Same

2022-07-25 18:01 UTC, waterplea commented on projects/demo/src/modules/themes/material/material.style.less
> +        &[data-state='hover'] {
And here

2022-07-25 18:01 UTC, waterplea commented on projects/kit/components/input-files/input-files.style.less
> +    &[data-state='hover'] {
And here

2022-07-27 08:31 UTC, waterplea approved these changes

2022-07-27 08:31 UTC, waterplea commented on projects/addon-preview/components/preview-dialog/preview-dialog.style.less
>          opacity: var(--tui-disabled-opacity);
This is already defined in wrapper/base.less

2022-07-27 08:31 UTC, waterplea commented on projects/demo/src/modules/components/button/examples/4/index.less
>      &[data-state='disabled'] {
I believe there's a mixin for that as well. Better to use those so it's centralized.

2022-07-27 08:31 UTC, waterplea commented on projects/demo/src/modules/themes/bootstrap/bootstrap.style.less
>          &._focused:after {
Focused state also has a mixin

2022-07-27 08:31 UTC, waterplea commented on projects/demo/src/modules/themes/material/material.style.less
>          &._focused {
Same here. Let's use mixins whenever possible

2022-07-27 08:31 UTC, waterplea commented on projects/kit/components/input-files/input-files.style.less
>      &[data-state='disabled'] {
Same here

2022-07-27 10:58 UTC, merged