feat(cdk): schematics shouldn't be a direct depended on cdk
Tinkoff/taiga-ui pull request #2414
Opened 2022-08-19 08:30 UTC by splincode

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2413

## What is the new behavior?

```
$ rm -rf dist
$ nx test-schematics cdk
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-08-19 08:42 UTC, nsbarsukov approved these changes

2022-08-20 12:40 UTC, splincode commented on scripts/postbump.ts
> +    overwriteVersion(resolve(`./projects/core/constants/version.ts`), `VERSION`, version);
changed

2022-08-22 06:54 UTC, vladimirpotekhin approved these changes

2022-08-22 14:00 UTC, nsbarsukov requested changes

2022-08-22 14:00 UTC, nsbarsukov commented on projects/taiga-schematics/schematics/ng-add/constants/version.ts
> +export const TUI_SCHEMATICS_VERSION = `2.60.0`;
May be we should remove nesting inside this schematics-package ?

I am not sure that we need folder `schematics` inside package `taiga-schematics`

2022-08-22 14:47 UTC, splincode commented on projects/core/constants/version.ts
> +import {TUI_VERSION} from '@taiga-ui/cdk/constants/version';
fixed

2022-08-22 14:47 UTC, splincode commented on projects/taiga-schematics/schematics/ng-add/constants/version.ts
> +export const TUI_SCHEMATICS_VERSION = `2.60.0`;
fixed

2022-08-23 07:36 UTC, nsbarsukov requested changes
Probably, you should also change this line

https://github.com/Tinkoff/taiga-ui/blob/6c13da56c6ae928db314bfe21321779d7b9dfb39/projects/taiga-schematics/package.json#L24

<img width="797" alt="Screenshot 2022-08-23 at 10 35 58" src="https://user-images.githubusercontent.com/35179038/186099415-f9361211-91aa-416f-b37e-2715557e3d6e.png">

2022-08-23 07:39 UTC, nsbarsukov commented
@vladimirpotekhin review again, please 

(I hope we didn't break something :peka:)

2022-08-23 08:49 UTC, splincode commented
@nsbarsukov @vladimirpotekhin fixed

2022-08-23 11:17 UTC, nsbarsukov approved these changes

2022-08-23 11:32 UTC, merged