chore(cdk): add textfield-controller migration
Tinkoff/taiga-ui pull request #2445
Opened 2022-08-23 13:48 UTC by vladimirpotekhin

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes # 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-08-24 14:51 UTC, splincode approved these changes

2022-08-25 15:56 UTC, nsbarsukov requested changes

2022-08-25 15:56 UTC, nsbarsukov commented on projects/cdk/schematics/ng-update/constants/templates.ts
> +            withTagNames: ['tui-input-card', 'tui-input-tag', 'tui-multiselect'],
```suggestion
            withTagNames: ['tui-input-card', 'tui-input-tag', 'tui-multi-select'],
```

2022-08-25 15:56 UTC, nsbarsukov commented on projects/cdk/schematics/ng-update/constants/templates.ts
> +            withTagNames: ['tui-input-card', 'tui-input-tag', 'tui-multiselect'],
```suggestion
            withTagNames: ['tui-input-card', 'tui-input-tag', 'tui-multi-select'],
```

2022-08-28 16:02 UTC, vladimirpotekhin commented on projects/cdk/schematics/ng-update/constants/templates.ts
> +            withTagNames: ['tui-input-card', 'tui-input-tag', 'tui-multiselect'],
fixed

2022-08-29 07:13 UTC, vladimirpotekhin commented
@nsbarsukov review again, please)

2022-08-29 08:09 UTC, nsbarsukov commented on projects/cdk/schematics/ng-update/constants/templates.ts
> +            withTagNames: ['tui-input-tag', 'tui-multiselect'],
I've found new one)

```suggestion
            withTagNames: ['tui-input-tag', 'tui-multi-select'],
```

2022-08-29 08:09 UTC, nsbarsukov approved these changes

2022-08-29 10:06 UTC, merged