feat(kit): `Push` add new component
Tinkoff/taiga-ui pull request #2469
Opened 2022-08-25 13:54 UTC by waterplea

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes # 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

2022-08-25 14:04 UTC, vladimirpotekhin commented on projects/demo/src/modules/components/push/push.template.html
> +                Для использования импортировать модуль
eng

2022-08-26 06:59 UTC, splincode approved these changes

2022-08-26 08:05 UTC, nsbarsukov requested changes

2022-08-26 08:05 UTC, nsbarsukov commented on projects/kit/components/push/push-alert.component.ts
> +export class TuiPushAlertComponent {
`changeDetection: ChangeDetectionStrategy.OnPush` ?

2022-08-26 08:05 UTC, nsbarsukov commented on projects/kit/components/push/push.template.html
> +<div class="t-actons">
```suggestion
<div class="t-actions">
```
?

2022-08-26 08:05 UTC, nsbarsukov commented on projects/kit/components/push/push.style.less
> +.t-actons {
```suggestion
.t-actions {
```
?

2022-08-26 08:51 UTC, waterplea commented on projects/demo/src/modules/app/pages.ts
> +        section: $localize`Patterns`,
Nope, my mistake from initially working in proprietary. Fixed.

2022-08-26 08:52 UTC, waterplea commented on projects/demo/src/modules/app/pages.ts
> +        route: `/push`,
Fixed

2022-08-26 08:55 UTC, waterplea commented on projects/demo/src/modules/components/push/push.template.html
> +                (close)="onClose()"
Fixed

2022-08-26 08:56 UTC, waterplea commented on projects/kit/components/push/push-alert.template.html
> +        alt=""
This image serves decorative purposes. Let's not bloat inputs for that unless we have to.

2022-08-26 08:56 UTC, waterplea commented on projects/kit/components/push/push-alert.component.ts
> +export class TuiPushAlertComponent {
Fixed

2022-08-26 08:56 UTC, waterplea commented on projects/kit/components/push/push.template.html
> +<div class="t-actons">
Fixed

2022-08-26 08:57 UTC, waterplea commented on projects/kit/components/push/push.style.less
> +.t-actons {
Fixed

2022-08-26 09:42 UTC, waterplea commented on projects/demo/src/modules/components/push/examples/1/index.less
> +    width: 22.5rem;
Done

2022-08-26 09:53 UTC, nsbarsukov approved these changes

2022-08-26 11:10 UTC, merged