fix(addon-doc): fix unexpected empty space in navigation
Tinkoff/taiga-ui pull request #2753
Opened 2022-09-23 12:20 UTC by vladimirpotekhin

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2532 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-09-23 13:33 UTC, nsbarsukov approved these changes

2022-09-26 06:57 UTC, waterplea commented on projects/addon-doc/src/components/navigation/navigation.template.html
> +                        <ng-template>
We used eager expand here so that parent `routerLinkActive` could know about active child and change color even when closed.

2022-09-27 08:48 UTC, waterplea approved these changes
Will we add a little migration to add this directive to blank `ng-template` inside `tui-expand` for those who already had that issue?

2022-09-29 11:04 UTC, nsbarsukov requested changes

2022-09-29 11:04 UTC, nsbarsukov commented on projects/demo/src/modules/components/expand/examples/import/insert-template.md
> +  <ng-template tuiExpandContent>...</ng-template>
https://user-images.githubusercontent.com/35179038/193015276-91775e3e-e68a-46a7-a06e-5009ac1103a8.mov

2022-10-03 10:55 UTC, nsbarsukov approved these changes

2022-10-03 10:58 UTC, merged