feat(kit): add date input options DI token for custom icons
Tinkoff/taiga-ui pull request #2785
Opened 2022-10-01 23:12 UTC by alvaromartmart

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2756

## What is the new behavior?

This PR adds a `TUI_INPUT_DATE_OPTIONS` token that can be used to customize `iconCalendar` & `iconCalendarLarge` values, which are used to display the appropriate icon.
The implementation is based on what's seen on https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/components/select/select-options.ts, I followed the same approach to allow overriding options.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-10-01 23:13 UTC, alvaromartmart commented
Please let me know if the approach is the right one for supporting this customization.

2022-10-02 15:40 UTC, splincode approved these changes

2022-10-03 06:38 UTC, waterplea requested changes
Thank you for this PR, a few comments:

1. Let's reuse this token in `InputDateRange` and `InputDateTime` as well.
2. We can add `min` and `max` to this token too.
3. Please take a look at [how it is done](https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/components/input-time/input-time-options.ts#L17) in `InputTime`, where we have single icon, but it's `PolymorpheusContent` where size comes as context.

2022-10-03 06:58 UTC, alvaromartmart commented
> Thank you for this PR, a few comments:
> 
> 1. Let's reuse this token in `InputDateRange` and `InputDateTime` as well.

Shall I move the `input-date-options.ts` to `kit/tokens` folder then since now it's reused by several components?

> 2. We can add `min` and `max` to this token too.

👍 

> 3. Please take a look at [how it is done](https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/components/input-time/input-time-options.ts#L17) in `InputTime`, where we have single icon, but it's `PolymorpheusContent` where size comes as context.

Will do, thanks

2022-10-03 07:14 UTC, waterplea commented
> Shall I move the input-date-options.ts to kit/tokens folder then since now it's reused by several components?

Yes, let's move it so entry points are less entangled.

2022-10-03 07:25 UTC, alvaromartmart commented
Applied suggested changes

2022-10-03 08:09 UTC, waterplea commented
I believe you need to change templates too to enable that size based polymorpheus content for icons.

2022-10-03 12:42 UTC, alvaromartmart commented
> I believe you need to change templates too to enable that size based polymorpheus content for icons.

Done

2022-10-04 15:20 UTC, waterplea requested changes
Great! Thank you. One last thing, let's remove those `size` getters and just pass size from the controller. Our current design has the same icon for `m` and `l`, but that might not be the case for others who would want to override default icons.

2022-10-04 22:30 UTC, alvaromartmart commented
> Great! Thank you. One last thing, let's remove those `size` getters and just pass size from the controller. Our current design has the same icon for `m` and `l`, but that might not be the case for others who would want to override default icons.

I'm not sure I understand what you mean, are you referring to the ternary expression (` return tuiSizeBigger(this.textfieldSize.size) ? "l" : "s"`) or to the getter altogether? I used a `size` getter based on other instances in the code that implemented the same behaviour. Example:

https://github.com/alvaromartmart/taiga-ui/blob/8fd65e76655f398d0856d56b5e7a7d69ef9a98c6/projects/kit/components/input-tag/input-tag.component.ts#L219-L221

2022-10-05 07:25 UTC, waterplea commented
> > Great! Thank you. One last thing, let's remove those `size` getters and just pass size from the controller. Our current design has the same icon for `m` and `l`, but that might not be the case for others who would want to override default icons.
> 
> I'm not sure I understand what you mean, are you referring to the ternary expression (` return tuiSizeBigger(this.textfieldSize.size) ? "l" : "s"`) or to the getter altogether? I used a `size` getter based on other instances in the code that implemented the same behaviour. Example:
> 
> https://github.com/alvaromartmart/taiga-ui/blob/8fd65e76655f398d0856d56b5e7a7d69ef9a98c6/projects/kit/components/input-tag/input-tag.component.ts#L219-L221

Yes, the link you sent is just a getter to access private controller, it returns size "as is". In your code you narrow down size to only 's' or 'l':
```ts
    get size(): TuiSizeL | TuiSizeS {
        return tuiSizeBigger(this.textfieldSize.size) ? `l` : `s`;
    }
```
Change it to just returning `this.textfieldSize.size`, because otherwise it's impossible to override icon for 'm' size specifically.

2022-10-06 22:40 UTC, alvaromartmart commented
Hi, I believe this is done, please let me know if there's still anything pending

2022-10-07 08:15 UTC, waterplea approved these changes

2022-10-07 08:16 UTC, merged