feat(kit): `InputDate` add min/max support for native input date
Tinkoff/taiga-ui pull request #4519
Opened 2023-05-23 08:47 UTC by vladimirpotekhin

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

part of #1358

## What is the new behavior?

2023-05-23 09:40 UTC, waterplea approved these changes

2023-05-23 09:40 UTC, waterplea commented on projects/kit/components/input-date/native-date/native-date.component.ts
> +        return this.host.max.toString('YMD', '-');
I think that's just `toJSON()`.

2023-05-25 09:39 UTC, nsbarsukov approved these changes

2023-05-25 09:39 UTC, nsbarsukov commented on projects/demo/src/modules/components/input-date/examples/6/index.html
> +    <tui-input-date
Cypress test fails.
See https://github.com/Tinkoff/taiga-ui/actions/runs/5059051359/jobs/9080189963?pr=4519

```
    (Attempt 1 of 2) native data picker
    1) native data picker
  1 passing (9s)
  1 failing
  1) InputDate
       native data picker:
CypressError: `cy.type()` can only be called on a single element.
Your subject contained 2 elements.
```

2023-05-25 09:46 UTC, nsbarsukov requested changes

2023-05-25 09:48 UTC, nsbarsukov commented on projects/demo/src/modules/components/input-date/examples/6/index.html
> +        [min]="min"
https://github.com/Tinkoff/taiga-ui/assets/35179038/840e1eca-006e-4bf6-98e3-f4e291f24ff7

2023-05-26 07:18 UTC, vladimirpotekhin commented on projects/demo/src/modules/components/input-date/examples/6/index.html
> +        [min]="min"
Safari doesn't show min/max in native picker ( we decided to remove the example from the demo, but keep the functionality for the future

2023-05-26 07:20 UTC, nsbarsukov approved these changes

2023-05-26 08:57 UTC, merged