feat(addon-mobile): `PullToRefresh` allow customization
Tinkoff/taiga-ui pull request #4530
Opened 2023-05-24 14:17 UTC by waterplea

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Part of #3979

## What is the new behavior?

2023-05-25 08:58 UTC, vladimirpotekhin approved these changes

2023-05-26 09:05 UTC, waterplea commented on projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts
> +        return this.context.$implicit / (this.threshold * 1.5);
Added comment

2023-05-26 13:30 UTC, nsbarsukov approved these changes

2023-05-26 13:31 UTC, nsbarsukov commented on projects/demo/src/modules/components/pull-to-refresh/examples/1/index.ts
> -import {TUI_LOADED} from '@taiga-ui/addon-mobile';
Do we keep backward compatibility for this token somehow ?

2023-05-26 13:39 UTC, nsbarsukov requested changes

2023-05-26 13:39 UTC, nsbarsukov commented on projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts
> +export const TUI_LOADED = TUI_PULL_TO_REFRESH_LOADED;
BC ?

2023-05-26 13:43 UTC, nsbarsukov approved these changes

2023-05-29 08:44 UTC, merged