feat(kit): `InputMonth` add ability to use native picker on mobile
Tinkoff/taiga-ui pull request #4709
Opened 2023-06-19 16:29 UTC by waterplea

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1358

## What is the new behavior?

2023-06-19 17:23 UTC, splincode approved these changes

2023-06-19 18:20 UTC, vladimirpotekhin commented
something wrong after click on cleaner:

https://github.com/Tinkoff/taiga-ui/assets/46284632/dcb71199-d439-4a08-be29-e89272f235f3

2023-06-19 20:33 UTC, waterplea commented
> something wrong after click on cleaner:
> 
> https://github.com/Tinkoff/taiga-ui/assets/46284632/dcb71199-d439-4a08-be29-e89272f235f3
> 
> 

Fixed

2023-06-20 07:06 UTC, vladimirpotekhin approved these changes

2023-06-20 07:09 UTC, vladimirpotekhin requested changes
on iphone open both native and taiga pickers now

2023-06-20 08:39 UTC, vladimirpotekhin approved these changes

2023-06-20 09:26 UTC, merged